### ISSUE TITLE
New business rule is required

### ISSUE THREAD

**Issue by cmonsalvec** [FKSAxell/ISII-WORKSHOPS-TOME#2]
**Is your feature request related to a problem? Please describe.**

This feature is not related to a problem. It is related to a new policy of the organization. 

Based on the impact of the pandemic in the 2020 results, the board of the company has approved a new business rule (policy) beginning january 2021, that needs to be included in our product. 

**Describe the solution you'd like**

The new business rule establishes: If the customer is male, over 25 and younger than 45 then it is needed to subtract $100 from the base premium.

Therefore, we ask you to modify the premium calculation adding this new rule. 

**Describe alternatives you've considered**

There is no alternative to be considered.

**Additional context**

I will provide you with more information if needed

Best regards,

**Comment by kellycastrof** [comment]
We'll process your new business rule.

**Comment by kellycastrof** [comment]
We'll process your new business rule.

**Comment by kellycastrof** [comment]
We'll process your new business rule.

**Comment by kellycastrof** [comment]
We will proceed to process the request, @jose598   will be the assigned analyst, @ltvargas  will develop the solution, and @FKSAxell   will perform the tests

**Comment by jose598** [comment]
Hi @cmonsalvec . Please check it out this document which has the specifications of your new [requirement.[](url)](url
[tickeforMonsalvec.docx](https://github.com/jose598/ISII-WORKSHOPS-TOME/files/5851580/tickeforMonsalvec.docx)
)

**Comment by cmonsalvec** [comment]
Dear @jose598 ,

Thanks, I agree with the time estimation and with resources you need for developing this new feature. Therefore, the access to our facilities is granted. I do also agree with the scenarios you described in the table, if all of them work like that I and all my company will be happy.

**Comment by jose598** [comment]
@cmonsalvec  Thank you! 
@ltvargas will develop your new feature and @FKSAxell  will perfom the tests.

**Comment by ltvargas** [comment]
We solved the issue:  We solved the issue: if the customer is male, over 25 and younger than 45 then it is needed to subtract $100 from the base premium.

https://github.com/jose598/ISII-WORKSHOPS-TOME/blob/692eb81bc1c30247586c7da6f4ef5ae538f8b899/ec.edu.espol.workshops.second/src/main/java/ec/edu/espol/workshops/second/CarInsurance.java#L85-L87

**Comment by kellycastrof** [comment]
@cmonsalvec , now @FKSAxell will perform the test

**Comment by cmonsalvec** [comment]
Thanks @kellycastrof

**Comment by FKSAxell** [comment]
Hi, @cmonsalvec 
[TOME-TestPlan.docx](https://github.com/jose598/ISII-WORKSHOPS-TOME/files/5852090/TOME-TestPlan.docx)
Please check it out this document which has the specifications of test plan.

**Comment by cmonsalvec** [comment]
Dear @FKSAxell ,

Yes, those are the scenarios our organization is willing to use in the software. If all those scenarios work we will be happy enough.

**Comment by kellycastrof** [comment]
Dear @cmonsalvec 
This is the result of our tests.
All cases passed.
[TOME-TestPlan-Result.docx](https://github.com/jose598/ISII-WORKSHOPS-TOME/files/5852393/TOME-TestPlan-Result.docx)

Please tell us if you accept the solution that has been proposed.

**Comment by cmonsalvec** [comment]
Excellent news @kellycastrof 

We are looking forward being able to use the new version of the product

**Comment by kellycastrof** [comment]
Dear, @cmonsalvec 
The solution is completed, now the programmer @ltvargas  will release the new software version for you.

**Comment by cmonsalvec** [comment]
Thanks @kellycastrof , i will wait for @ltvargas instructions

**Comment by ltvargas** [comment]
The implementation of the new business rule is in the new branch Issue_Management in CarInsurance class, you can follow the next directory: ISII-WORKSHOPS-TOME/ec.edu.espol.workshops.second/src/main/java/ec/edu/espol/workshops/second/

To test the functionality, the client's characteristics must be placed in the following line: 
https://github.com/jose598/ISII-WORKSHOPS-TOME/blob/692eb81bc1c30247586c7da6f4ef5ae538f8b899/ec.edu.espol.workshops.second/src/main/java/ec/edu/espol/workshops/second/CarInsurance.java#L17-L18
For example: a client who meets the validity of his license, male, age 32 and married, receives a premium of $ 400.
As we see in the example image

![image](https://user-images.githubusercontent.com/52353943/105421923-e1a74500-5c10-11eb-9513-38d0bc6115d9.png)
Is the solution correct? @cmonsalvec

**Comment by cmonsalvec** [comment]
Dear @ltvargas,

Thanks, we will follow your instructions and we will begin to use the new version of the product.

**Comment by kellycastrof** [comment]
Dear, @cmonsalvec 
When you finish, please let us know if you are satisfied with the solution or if you had any problems, we would like to know to solve them.

**Comment by cmonsalvec** [comment]
Dear @kellycastrof 

My organization has already been using the software and everybody looks happy with it. Good job. Thanks.
